version: '3.8'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "8080:8080"

  myapp:
    build: .
    depends_on:
      - ollama
    ports:
      - "5001:5000"
    env_file:
      - src/.env