FROM python:3.10.11-slim

WORKDIR /app

# curl 및 ollama 설치
RUN apt-get update && apt-get install -y curl && \
    curl -fsSL https://ollama.com/install.sh | sh && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# ollama 서버 시작을 위한 entrypoint 스크립트 복사
COPY ollama-entrypoint.sh /ollama-entrypoint.sh
RUN chmod +x /ollama-entrypoint.sh

# ollama 서버 실행
CMD ["/ollama-entrypoint.sh"]
